// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewgsnmjcufzqvaaureah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3Z3NubWpjdWZ6cXZhYXVyZWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTk0ODMsImV4cCI6MjA3MTc5NTQ4M30.w9_yrayhHo2WSoKbHUgv40rb-YZEFcDqTxVRk4ScsUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});